# -*- coding: utf-8 -*-
"""Fetcher

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JTuLzz6Gk-xcPHsTw3PmwFvvgV7lIP-K
"""

import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta
from google.colab import files

tickers = ['NVDA', 'SPY']

end_date = datetime.today()
print(end_date)

years = timedelta(days = 365)
start_date = end_date - years*3
print(start_date)

close = pd.DataFrame()
df = close

for ticker in tickers:
  data = yf.download(ticker, start = start_date, end = end_date)
  df[ticker] = data['Close']

print(df)

df.to_excel('df.xlsx')
files.download('df.xlsx')

import matplotlib

ask = input("Ticker please! ")

stok_df = yf.download(ask)
ticker = yf.Ticker(ask)
stock_df = ticker.history(start=start_date, end=end_date)
stock_df['Close'].plot(title="Stock Price")

close2 = pd.DataFrame(ticker.dividends)
close2.index = pd.to_datetime(close2.index)
close2 = close2.tz_localize(None)
print(close2)

close2.to_excel('df2.xlsx')
files.download('df2.xlsx')